---
# tasks file for install-elastic 
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  

- name: Copy elastic installation file to the host
  copy:
    src: '{{ installation_files }}/elasticsearch-{{ elastic_version }}.deb'
    dest: '{{ installation_files }}/elasticsearch.deb'
    
- name: install elasticsearch 
  command: dpkg -i {{ installation_files }}/elasticsearch.deb
  
- name: systemctl daemon-reload 
  command: systemctl daemon-reload
  
- name: enable elasticsearch service
  command: systemctl enable elasticsearch.service
