---
# tasks file for install-samba
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: copy samba installation files
  copy:
    src: '{{ installation_files }}/samba'
    dest: '{{ installation_files }}'
    
- name: install samba 
  command: dpkg -R --install {{ installation_files }}/samba/

- name: systemctl daemon-reload 
  command: systemctl daemon-reload
  
- name: enable samba service
  command: systemctl enable smbd.service
