---
# tasks file for install-elastic-agent
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  

- name: Copy elastic agent installation file to the host
  copy:
    src: '{{ installation_files }}/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz'
    dest: '{{ installation_files }}/elastic-agent.tar.gz'
    
- name: Delete /elastic-agent directory
  shell: 'rm -rf /elastic-agent*'  

- name: extract elastic-agent.tar.gz 
  command: 'tar -xf {{ installation_files }}/elastic-agent.tar.gz -C /'

- name: move /elastic-agent* directory to /elastic-agent
  shell: 'mv /elastic-agent-{{ elastic_agent_version }}-linux-x86_64 /elastic-agent'  