---
# tasks file for install-cifs

- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: copy cifs-utils installation files
  copy:
    src: '{{ installation_files }}/cifs-utils'
    dest: '{{ installation_files }}'
    
- name: install cifs-utils 
  command: dpkg -R --install {{ installation_files }}/cifs-utils/
