---
### besme allah
### author: ali.ahmadi

- hosts: es-elastic-agent
  become: yes
  tasks:   
  - import_role:
      name: update-ca-certificates
  - import_role:
      name: install-elastic-agent
  - import_role:
      name: config-elastic-agent
   