---
### besme allah
### author: ali.ahmadi

- hosts: all
  become: yes
  tasks:   
  - import_role:
      name: update-ca-certificates
      
- hosts: es-fleet-server
  become: yes
  tasks:   
  - import_role:
      name: install-elastic-agent
      
- hosts: es-fleet-server
  become: yes
  tasks:   
  - import_role:
      name: config-elastic-agent
   