---
### besme allah
### author: ali.ahmadi
##- hosts: localhost
##  connection: local
##  become: yes
##  vars_files:
##    - vars/user-inputs.yaml
##  tasks:
##  - name: Confirm defaults on all
##    pause:
##      prompt: "do you want to defaults on all? (yes/no)"
##    register: confirm_defaults_on_all
##    
##  - name: Confirm install-elastic on es-master
##    pause:
##      prompt: "do you want to install-elastic on es-master? (yes/no)"
##    register: confirm_install_elastic_es_master
##    
##  - name: Confirm make-certificate on initial-master
##    pause:
##      prompt: "do you want to install-elastic on es-master? (yes/no)"
##    register: confirm_make_certificate_on_initial_master


- hosts: all
  become: yes
  #vars_files:
  #  - vars/user-inputs.yaml
  roles:
    - role: defaults
      #when: confirm_defaults_on_all.user_input | bool
      
- hosts: es-snapshot-share
  become: yes
  tasks:   
  - import_role:
      name: install-samba
  - import_role:
      name: config-samba            

- hosts: es-master
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
      
### mount share on all elastic nodes es-master, es-data-hot, es-data-warm , es-ingest
- hosts: es-master
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
      
- hosts: es-data-hot
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
      
- hosts: es-data-warm
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
      
- hosts: es-ingest
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
### end mount share on all elastic nodes

- hosts: es-master
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
      
- hosts: initial-master
  become: yes
  tasks:   
  - import_role:
      name: make-certificate
      
- hosts: es-master
  become: yes
  tasks:   
  - import_role:
      name: config-elastic
     
- hosts: es-data-hot
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
  - import_role:
      name: config-elastic
      
- hosts: initial-master
  become: yes
  tasks:   
  - import_role:
      name: setupusers-elastic
            
- hosts: es-kibana
  become: yes
  tasks:   
  - import_role:
      name: install-kibana
  - import_role:
      name: config-kibana
     
- hosts: initial-master
  become: yes
  tasks:   
  - import_role:
      name: config-ilm
     
- hosts: es-data-warm
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
  - import_role:
      name: config-elastic
      
- hosts: es-ingest
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
  - import_role:
      name: config-elastic
