---
### besme allah
### author: ali.ahmadi

- hosts: all
  become: yes
  roles:
    - role: defaults      
 
- hosts: es-master
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
      
- hosts: initial-master
  become: yes
  tasks:   
  - import_role:
      name: make-certificate
      
- hosts: all
  become: yes
  tasks:   
  - import_role:
      name: update-ca-certificates
      
- hosts: es-master
  become: yes
  tasks:   
  - import_role:
      name: config-elastic
      
- hosts: initial-master
  become: yes
  tasks:   
  - import_role:
      name: setupusers-elastic
            
- hosts: es-kibana
  become: yes
  tasks:   
  - import_role:
      name: install-kibana
  - import_role:
      name: config-kibana
     
- hosts: initial-master
  become: yes
  tasks:   
  - import_role:
      name: config-ilm
