---
### besme allah
### author: ali.ahmadi
##- hosts: localhost

- hosts: all
  become: yes
  #vars_files:
  #  - vars/user-inputs.yaml
  roles:
    - role: defaults
      #when: confirm_defaults_on_all.user_input | bool

      
- hosts: es-data-warm
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
      
- hosts: es-ingest
  become: yes
  tasks:   
  - import_role:
      name: install-cifs
  - import_role:
      name: mount-share
      
- hosts: es-data-warm
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
  - import_role:
      name: config-elastic
      
- hosts: es-ingest
  become: yes
  tasks:   
  - import_role:
      name: install-elastic
  - import_role:
      name: config-elastic
